apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ssemikeev/colorbot_deployment.git
    path: charts/argocd
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
